[IPL-99] Set 200 response by default in webhook
conekta/customer-magento-plugin pull request #21
Opened 2022-07-19 22:43 UTC by ElvisHeredia

# Detalle del PR

## Descripción
Se requiere designar como respuesta por default un 200 en los casos que el evento recibido por el webhook no sea necesario ser procesado 

## Tarea/Issue relacionada con JIRA
[IPL-99](https://conekta.atlassian.net/browse/IPL-99)

## Motivación y Contexto
Actualmente hay 2 casos de merchants enterprise en los que utilizan la versión paga de Magento (Adobe Commerce 2.4.2 p2), los cuales al tener el plugin en modo pruebas todo funciona de manera correcta, sin embargo, cuando pasan a modo productivo y llegan al punto de seleccionar el método de pago, entra en un bucle de eventos de order.updated y customer.updated, dejando la pantalla en blanco.

## Tipos de Cambios

- [ ] Cambio en la documentación / refactorización / actualización de dependencia
- [x] Corrección de errores (cambio que soluciona un problema)
- [ ] Nueva característica (cambio que agrega funcionalidad)
- [ ] Cambio de comportamiento (corrección o característica que cambiara la funcionalidad existente)

## Checklist

- [x] Mi código sigue el estilo de codificación de proyecto.
- [ ] Mi cambio requiere un cambio en la documentación.
- [ ] He actualizado la documentación correspondiente.
- [ ] Agregue los tests para cubrir mis cambios.
- [ ] Todos los test nuevos y existen pasaron correctamente.
- [x] Actualice el changelog.

## Evidencias

## Convención de merge
#### Este repositorio usa [Gitflow](https://www.atlassian.com/es/git/tutorials/comparing-workflows/gitflow-workflow)
<table style="width:100%">
  <tr>
    <th>Branch desde</th>
    <th>Branch hacia</th>
    <th>Merge commit</th>
    <th>Squash and Merge</th>
  </tr>
  <tr>
    <td>feature/</td>
    <td>develop</td>
    <td>&#10060</td>	
    <td>&#9989</td>
  </tr>
  <tr>
    <td>hotfix/</td>
    <td>master - release/</td>
    <td>&#10060</td>
    <td>&#9989</td>
  </tr>
  <tr>
    <td>fix/</td>
    <td>release/x.x.x</td>
    <td>&#10060</td>
    <td>&#9989</td>
  </tr>
  <tr>
    <td>release/x.x.x</td>
    <td>master</td>
    <td>&#9989</td>
    <td>&#10060</td>
  </tr>
  <tr>
    <td>backport/</td>
    <td>develop</td>
    <td>&#9989</td>
    <td>&#10060</td>
  </tr>
</table>

¿Qué pasa si hago <b>merge commit</b> cuando debía hacer un <b>squash</b>?
- Nada grave, simplemente nos estaríamos llevando commits innecesarios al branch donde mergeemos, ejemplo, si en mi branch feature/ tengo 15 commits y los comentarios no son descriptivos (fix, fix tests, working) me estaría llevando todos esos a develop, cuando con el Squash voy a llevar uno solo.

¿Qué pasa si hago <b>Squash</b> cuando debía hacer un <b>merge commit</b>?
- En este caso no estaríamos cumpliendo la función que esperamos que es llevar los commits de un branch a otro para emparejarlos, por ejemplo, cuando mergeamos una release a master, el objetivo es dejar parejos develop y master, y si usamos squash como estrategia de merge van a seguir teniendo commits distintos, por lo que en el siguiente release podríamos tener conflictos.
---------------------------------

2022-07-20 00:55 UTC, agatto-conekta commented on etc/module.xml
> +    <module name="Conekta_Payments" setup_version="4.1.1">
perdon la ignorancia, esta bien este salto de version?

2022-07-20 00:55 UTC, agatto-conekta commented on etc/module.xml
> +    <module name="Conekta_Payments" setup_version="4.1.1">
veo bien este PR, dejo esa duda nada mas

2022-07-21 13:44 UTC, afalla-conekta requested changes

2022-07-21 13:44 UTC, afalla-conekta commented on Controller/Webhook/Index.php
> +                    $response = self::HTTP_OK_REQUEST_CODE;
Para este caso ya existe una libreria que retorna estos status code:

`use Symfony\Component\HttpFoundation\Response as HttpCodeResponse;`

Para invocar en esta caso:

`HttpCodeResponse::HTTP_OK,`

2022-07-21 13:44 UTC, afalla-conekta commented on Controller/Webhook/Index.php
> +                    $response = self::HTTP_OK_REQUEST_CODE;
Esto no cambia algún test unitario?

2022-07-21 14:48 UTC, ElvisHeredia commented on etc/module.xml
> +    <module name="Conekta_Payments" setup_version="4.1.1">
Lo que pasa e que no se había actualizado la versión del plugin en este archivo, esto no es inconveniente es mas para que Magento sepa cual es la versión que esta instalada

2022-07-21 15:07 UTC, ElvisHeredia commented on Controller/Webhook/Index.php
> +                    $response = self::HTTP_OK_REQUEST_CODE;
En realidad esa no esta disponible puede ser la versión de Magento, use `Laminas\Http\Response`

2022-07-21 15:40 UTC, agatto-conekta commented on Controller/Webhook/Index.php
> +        $response = Response::STATUS_CODE_400;
no deberia empezar por defecto en 200, y hacer un return Response::STATUS_CODE_400; en el if method != post de mas abajo? 
para mantener consistencia con el otro cambio

2022-07-21 15:51 UTC, ElvisHeredia commented on Controller/Webhook/Index.php
> +        $response = Response::STATUS_CODE_400;
ajustado

2022-07-21 15:56 UTC, afalla-conekta approved these changes

2022-07-21 16:03 UTC, agatto-conekta approved these changes

2022-07-27 19:38 UTC, merged